name: Unit Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 👍 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Install dependencies
        run: |
          go mod download
          go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum --format pkgname-and-test-fails --raw-command -- go test -v -race -json -coverprofile=coverage.out ./...

  lint:
    name: 💅 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod download

      - name: Go vet
        run: go vet ./...

      - name: Run Linter
        uses: morphy2k/revive-action@v2
        with:
          config: revive.toml
          exclude: |
            examples/...

  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: '${{ secrets.ACCESS_TOKEN }}'
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install -U commitizen

      - name: Check commits
        run: cz check --rev-range origin/main..HEAD

      - name: Check PR title
        run: cz check -m "${{ github.event.pull_request.title }}"