name: Release

on:
  push:
    branches:
      - main

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_NAME }}
  GOPRIVATE: github.com/Drafteame

permissions:
  contents: write

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version"
    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: "${{ secrets.ACCESS_TOKEN }}"
          ref: "main"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          git_name: ${{ secrets.GIT_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          changelog_increment_filename: body.md

      - name: Print Version
        run: echo "Bumped to version v${{ env.REVISION }}"

      - name: Trim body to 125000 characters
        run: |
          if [ $(wc -c < body.md) -gt 125000 ]; then
            head -c 125000 body.md > body.md
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: "true"

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
